{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"postgres_exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INSERT calls/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_by_verb_calls{verb=\"INSERT\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SELECT calls/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_by_verb_calls{verb=\"SELECT\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE calls/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_by_verb_calls{verb=\"DELETE\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"postgres_exporter:9187\"}[5m]) * 1000)",
     "legendFormat": "mCPU"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"postgres_exporter:9187\", state=\"active\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  }
 ]
}